spring.application.name=fintrack-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fintrack}
spring.datasource.username=${DB_USERNAME:fintrack}
spring.datasource.password=${DB_PASSWORD:fintrack}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true